services:
  - type: web
    name: bollywood-movie-recommender
    runtime: python
    plan: free
    buildCommand: pip install -r deploy/streamlit_public/requirements.txt
    startCommand: streamlit run deploy/streamlit_public/app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
